<a href="https://colab.research.google.com/github/pakvadim151/Netology/blob/main/Homework_VadimPak_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Домашнее задание «Библиотека numpy. Вычислительные задачи»


Задание 1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будетarray([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [ ]:
import numpy as np

In [ ]:
N = 10
np.array(list(range(N-1, -1, -1)))

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [ ]:
np.arange(N-1, -1, -1)

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [ ]:
A = np.diag(np.arange(N-1, -1, -1), k=0)
A

array([[9, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 8, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 7, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 6, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 4, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 3, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 2, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [ ]:
A.trace()

45

In [ ]:
A.sum()

45

#Задание 3

Решите систему уравнений:

4x + 2y + z = 4

x + 3y = 12

5y + 4z = -3

In [ ]:
A = np.array([
    [4, 2, 1],
    [1, 3, 0],
    [0, 5, 4]
])

In [ ]:
b = np.array([4, 12, -3])

In [ ]:
np.linalg.solve(A, b)

array([ 0.46666667,  3.84444444, -5.55555556])

In [ ]:
np.linalg.inv(A) @ b

array([ 0.46666667,  3.84444444, -5.55555556])

#Задание 4

Имеется матрица покупок в интернет-магазине. Столбец А - ID пользователя. Остальные столбцы - количество покупок категорий товаров этим пользователем:

Матрица в виде numpy array

In [ ]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

In [ ]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

Найдите самого похожего пользователя. Т. е. посчитайте косинусное сходство между этим пользователем и всеми пользователями из массива user_stats

In [ ]:
users_stats.shape

(10, 6)

In [ ]:
s = users_stats @ next_user_stats
s

array([1, 5, 2, 5, 2, 0, 0, 3, 0, 0])

In [ ]:
next_user_length = np.linalg.norm(next_user_stats)
next_user_length

2.23606797749979

In [ ]:
users_length = np.linalg.norm(users_stats)
users_length

9.539392014169456

In [ ]:
users_length_rows = np.linalg.norm(users_stats, axis = 1)
users_length_rows

array([2.23606798, 2.64575131, 2.23606798, 2.82842712, 2.23606798,
       5.        , 1.        , 1.41421356, 3.31662479, 4.69041576])

In [ ]:
cosines = (s/(next_user_length*users_length_rows)).reshape(-1,1)
cosines

array([[0.2       ],
       [0.84515425],
       [0.4       ],
       [0.79056942],
       [0.4       ],
       [0.        ],
       [0.        ],
       [0.9486833 ],
       [0.        ],
       [0.        ]])

In [ ]:
cosines.argmax()

7

In [ ]:
users_stats[7]

array([0, 1, 1, 0, 0, 0], dtype=int32)

Ответ:

Новый покупатель имеет наибольшее косинусное сходство с покупателем [7]